name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub (replace if you're using another registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #   - name: Build Docker image
      #     run: |
      #       docker build -t your-dockerhub-username/django-app .

      #   - name: Push to Docker Hub
      #     run: |
      #       docker push your-dockerhub-username/django-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-stock-app:latest
          build-args: |
            ALPHA_VANTAGE_API_KEY=${{secrets.ALPHA_VANTAGE_API_KEY}}
            DATABASE_URL=${{secrets.DATABASE_URL}}
            SECRET_KEY=${{secrets.SECRET_KEY}}
            DEBUG=${{secrets.DEBUG}}

  deploy:
    needs: build # (needs build This ensures that the deploy job runs after the build job)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Trigger deployment on Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
      # - name: Deploy to Render
      #   env:
      #     RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer $RENDER_API_KEY" \
      #       -H "Accept: application/json" \
      #       -H "Content-Type: application/json" \
      #       -d '{"clearCache": true}' \
      #       https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
